### ISSUE TITLE
docs status failing

### ISSUE THREAD

**Issue by mianasbat** [UCL/scikit-surgeryspeech#24]
The documentation status on the home page shows failing.

**Comment by tdowrick** [comment]
This was a bit fiddly to fix. Basically, pyaudio can't be build on the ReadTheDocs build server, so had to:

* create docs/requirements.txt without pyaudio listed
* Edit RTD settings to use above requirements file
* Create an environmental variable in RTD settings so we can detect if running on RTD server, if so, modify the setup.py file to remove pyaudio
* Use autodoc_mock_imports in conf.py, otherwise sphinx will error as it can't import pyaudio.
